const fs = require('fs');
const path = require('path');

const questionFiles = [
    'src/data/questions/starterQuestions.ts',
    'src/data/questions/moneyMath.ts',
    'src/data/questions/scenarioMCQ.ts',
    'src/data/questions/trueFalse.ts',
    'src/data/questions/dailyChallenges.ts',
    'src/data/questions/termMatch.ts'
];

let allSql = '-- FINIQ Questions Seed Data\n-- Generated by extract_questions.js\n\n';
allSql += 'INSERT INTO public.questions (id, type, topic, difficulty, question, answer, options, explanation, time_limit, min_rating, is_starter, event_context, fun_fact)\nVALUES\n';

const projectRoot = 'c:/FinIQ';
const sqlValues = [];

function escapeSql(str) {
    if (str === null || str === undefined || str === 'NULL') return 'NULL';
    if (typeof str === 'number') return str;
    if (typeof str === 'boolean') return str ? 'TRUE' : 'FALSE';
    return `'${String(str).replace(/'/g, "''")}'`;
}

questionFiles.forEach(file => {
    const fullPath = path.join(projectRoot, file);
    if (!fs.existsSync(fullPath)) return;
    const content = fs.readFileSync(fullPath, 'utf8');

    // More flexible regex to find objects with an 'id' property
    const regex = /\{[\s\S]*?id:\s*(["'])(.*?)\1[\s\S]*?\}/g;
    let match;

    while ((match = regex.exec(content)) !== null) {
        const objStr = match[0];

        // Extract fields using flexible regex
        const id = (objStr.match(/id:\s*(["'])(.*?)\1/) || [])[2];
        const type = (objStr.match(/type:\s*(["'])(.*?)\1/) || [])[2] || (file.includes('termMatch') ? 'term_match' : '');
        const topic = (objStr.match(/topic:\s*(["'])(.*?)\1/) || [])[2] || '';
        const difficulty = (objStr.match(/difficulty:\s*(\d+)/) || [])[1] || 0;

        // Handle Question/Term
        let question = (objStr.match(/question:\s*(["'])(.*?)\1/) || [])[2];
        if (!question && file.includes('termMatch')) {
            question = (objStr.match(/term:\s*(["'])(.*?)\1/) || [])[2];
        }

        // Handle Answer/Definition
        let answer = '';
        let answerMatch = objStr.match(/answer:\s*(["'])(.*?)\1/) || objStr.match(/answer:\s*(\d+(\.\d+)?)/);
        if (answerMatch) {
            answer = answerMatch[2] || answerMatch[1];
        } else if (file.includes('termMatch')) {
            const defMatch = objStr.match(/definition:\s*(["'])(.*?)\1/);
            if (defMatch) answer = defMatch[2];
        }

        // Options can be complex array
        let options = 'NULL';
        const optionsMatch = objStr.match(/options:\s*\[([\s\S]*?)\]/);
        if (optionsMatch) {
            const optsRaw = optionsMatch[1];
            const optsArr = [];
            const optItemRegex = /(["'])(.*?)\1|(\d+(\.\d+)?)/g;
            let optMatch;
            while ((optMatch = optItemRegex.exec(optsRaw)) !== null) {
                optsArr.push(optMatch[2] || optMatch[3]);
            }
            if (optsArr.length > 0) {
                options = `'${JSON.stringify(optsArr).replace(/'/g, "''")}'`;
            }
        }

        const explanationMatch = objStr.match(/explanation:\s*(["'])(.*?)\1/);
        const explanation = explanationMatch ? explanationMatch[2] : '';

        const timeLimit = (objStr.match(/timeLimit:\s*(\d+)/) || [])[1] || 'NULL';
        const minRating = (objStr.match(/minRating:\s*(\d+)/) || [])[1] || 'NULL';
        const isStarter = objStr.includes('isStarter: true') ? 'TRUE' : 'FALSE';
        const eventContext = (objStr.match(/event_context:\s*(["'])(.*?)\1/) || [])[2] || 'NULL';
        const funFact = (objStr.match(/fun_fact:\s*(["'])(.*?)\1/) || [])[2] || 'NULL';

        if (id && question) {
            sqlValues.push(`(${escapeSql(id)}, ${escapeSql(type)}, ${escapeSql(topic)}, ${difficulty}, ${escapeSql(question)}, ${escapeSql(answer)}, ${options}, ${escapeSql(explanation)}, ${timeLimit}, ${minRating}, ${isStarter}, ${escapeSql(eventContext)}, ${escapeSql(funFact)})`);
        }
    }
});

allSql += sqlValues.join(',\n') + ';\n';

fs.writeFileSync(path.join(projectRoot, 'finiq_questions_seed.sql'), allSql);
console.log(`Generated finiq_questions_seed.sql with ${sqlValues.length} questions.`);
